// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourProject.Data;

#nullable disable

namespace YourProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260907194100_AddConteudoUsuarioFk")]
    partial class AddConteudoUsuarioFk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("YourProject.Models.Conteudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_CONTEUDO");

                    b.Property<DateTime>("DataPublicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_PUBLICACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DESCRICAO_CONTEUDO");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NIVEL_CONTEUDO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TIPO_CONTEUDO");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TITULO_CONTEUDO");

                    b.Property<int>("UsuarioFk")
                        .HasColumnType("int")
                        .HasColumnName("USUARIOFK");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioFk");

                    b.ToTable("CONTEUDO");
                });

            modelBuilder.Entity("YourProject.Models.MetaFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_META");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(56)
                        .HasColumnType("varchar(56)")
                        .HasColumnName("NOME_META");

                    b.Property<DateTime>("Prazo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("PRAZO_META");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("STATUS_META");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("USUARIOFK");

                    b.Property<double>("Valor")
                        .HasColumnType("double")
                        .HasColumnName("VALOR_META");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("META_FINANCEIRA", (string)null);
                });

            modelBuilder.Entity("YourProject.Models.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_TRANSACAO");

                    b.Property<DateTime>("Data")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_TRANS")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("DESCRICAO_CONT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TIPO_TRANS");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("USUARIOFK");

                    b.Property<double>("Valor")
                        .HasColumnType("double")
                        .HasColumnName("VALOR_TRANS");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TRANSACAO", (string)null);
                });

            modelBuilder.Entity("YourProject.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("EMAIL_USUARIO");

                    b.Property<bool>("Endividado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ENDIVIDADO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOME_USUARIO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("SENHA_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("YourProject.Models.Conteudo", b =>
                {
                    b.HasOne("YourProject.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("YourProject.Models.MetaFinanceira", b =>
                {
                    b.HasOne("YourProject.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("YourProject.Models.Transacao", b =>
                {
                    b.HasOne("YourProject.Models.Usuario", "Usuario")
                        .WithMany("Transacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("YourProject.Models.Usuario", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
