CREATE DATABASE BD_CASHWISE;
USE BD_CASHWISE;
CREATE TABLE USUARIO (
    ID_USUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_USUARIO VARCHAR(256) NOT NULL,
    EMAIL_USUARIO VARCHAR(256) NOT NULL UNIQUE,
    SENHA_USUARIO VARCHAR(255) NOT NULL,
    ENDIVIDADO BOOLEAN NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CONTEUDO (
    ID_CONTEUDO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITULO_CONTEUDO VARCHAR(256) NOT NULL,
    DESCRICAO_CONTEUDO TEXT NOT NULL,
    TIPO_CONTEUDO ENUM('INVESTIMENTO','ECONOMIA','VALORIZACAO') NOT NULL,
    NIVEL_CONTEUDO ENUM('INICIANTE','INTERMEDIARIO','AVANCADO') NOT NULL,
    DATA_PUBLICACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIOFK INT NOT NULL,
    FOREIGN KEY (USUARIOFK) REFERENCES USUARIO (ID_USUARIO)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
    );


CREATE TABLE META_FINANCEIRA (
	ID_META INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_META VARCHAR (56) NOT NULL UNIQUE ,
    VALOR_META DOUBLE NOT NULL,
    PRAZO_META DATE NOT NULL,
    STATUS_META ENUM ('SIGA EM FRENTE', ' QUASE LA', 'CONCLUIDO') NOT NULL,
    USUARIOFK INT NOT NULL,
    FOREIGN KEY (USUARIOFK) REFERENCES USUARIO (ID_USUARIO)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
    );

CREATE TABLE TRANSACAO (
	ID_TRANSACAO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO_CONT TEXT NOT NULL,
    VALOR_TRANS DOUBLE NOT NULL,
    TIPO_TRANS ENUM ('RECEITA' , 'DESPESA') NOT NULL,
    DATA_TRANS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIOFK INT NOT NULL,
    FOREIGN KEY (USUARIOFK) REFERENCES USUARIO (ID_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    );
    
CREATE TABLE DASHBOARD (
ID_DASH INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
USUARIOFK INT NOT NULL,
SALDOTOTAL_DASH DOUBLE NOT NULL, 
GASTOSMENSAIS_DASH DOUBLE NOT NULL,
INVESTIMENTOTOTAIS_DASH DOUBLE NOT NULL, 
FOREIGN KEY (USUARIOFK) REFERENCES USUARIO (ID_USUARIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
    );






























CREATE VIEW VW_DASHBOARD AS
SELECT 
    U.ID_USUARIO,
    U.NOME_USUARIO,

   
    SUM(CASE WHEN T.TIPO_TRANS = 'RECEITA' THEN T.VALOR_TRANS ELSE 0 END) -
    SUM(CASE WHEN T.TIPO_TRANS = 'DESPESA' THEN T.VALOR_TRANS ELSE 0 END) AS SALDO_TOTAL,

    
    SUM(
        CASE 
            WHEN T.TIPO_TRANS = 'DESPESA' AND MONTH(T.DATA_TRANS) = MONTH(CURRENT_DATE())
            AND YEAR(T.DATA_TRANS) = YEAR(CURRENT_DATE())
            THEN T.VALOR_TRANS
            ELSE 0 
        END
    ) AS GASTOS_MENSAIS,

   
    SUM(
        CASE 
            WHEN T.TIPO_TRANS = 'RECEITA' AND T.DESCRICAO_CONT LIKE '%investimento%'
            THEN T.VALOR_TRANS
            ELSE 0 
        END
    ) AS INVESTIMENTOS_TOTAIS

FROM USUARIO U
LEFT JOIN TRANSACAO T ON U.ID_USUARIO = T.USUARIOFK
GROUP BY U.ID_USUARIO, U.NOME_USUARIO;